"""
08_tiler_config.py — Mojadata Tiler Configuration
===================================================
Generates a tiler.py script for the mojadata tiler that defines:
  - Bounding box from inventory layer
  - Classifier layers from inventory.gpkg attributes
  - Age layer from initial_age attribute
  - Disturbance layers (one per year, 2026-2075)
  - Mean annual temperature raster placeholder

Output: output/gcbm_input/tiler.py
"""

import json
from pathlib import Path

import geopandas as gpd

from config import (
    OUTPUT_DIR,
    CLASSIFIER_NAMES,
    SIM_START_YEAR,
    SIM_END_YEAR,
)


def generate_tiler_script(inventory_path=None):
    """
    Generate a mojadata tiler script based on the processed inventory and
    disturbance layers.

    Parameters:
        inventory_path: Path to inventory.gpkg (default: OUTPUT_DIR/inventory.gpkg)
    """
    print("=" * 60)
    print("08_tiler_config: Generating mojadata tiler configuration")
    print("=" * 60)

    if inventory_path is None:
        inventory_path = OUTPUT_DIR / "inventory.gpkg"

    # Read inventory to get bounding box
    inv = gpd.read_file(inventory_path)
    bounds = inv.total_bounds  # (minx, miny, maxx, maxy)

    # Disturbance layer is now a single GeoPackage with a year column
    dist_path = OUTPUT_DIR / "disturbances.gpkg"
    dist_gdf = gpd.read_file(dist_path)
    dist_years = sorted(dist_gdf["year"].unique())

    # Generate the tiler script
    script = _build_tiler_script(bounds, dist_years)

    out_path = OUTPUT_DIR / "tiler.py"
    with open(out_path, "w") as f:
        f.write(script)

    print(f"\n  Inventory bounding box: {bounds}")
    print(f"  Disturbance years: {len(dist_years)}")
    print(f"  Wrote {out_path}")
    return out_path


def _build_tiler_script(bounds, dist_years):
    """Build the tiler.py script content."""
    minx, miny, maxx, maxy = bounds

    dist_layer_lines = []
    for year in dist_years:
        dist_layer_lines.append(
            f'        DisturbanceLayer(\n'
            f'            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",\n'
            f'                        raw_filter="year = {year}"),\n'
            f'            year={year},\n'
            f'        ),'
        )

    dist_layers_str = "\n".join(dist_layer_lines)

    classifier_lines = []
    for clf in CLASSIFIER_NAMES:
        classifier_lines.append(
            f'        ClassifierLayer("{clf}", INV_PATH, "{clf}"),'
        )
    classifiers_str = "\n".join(classifier_lines)

    script = f'''"""
Mojadata tiler configuration for IWC Boothill GCBM simulation.

Auto-generated by 08_tiler_config.py.
Review and adjust paths before running.

Usage:
    python tiler.py
"""

from pathlib import Path

from mojadata.boundingbox import BoundingBox
from mojadata.layer.vectorlayer import VectorLayer
from mojadata.layer.rasterlayer import RasterLayer
from mojadata.layer.attribute import Attribute
from mojadata.config import (
    BoundingBox as BBox,
    ClassifierLayer,
    DisturbanceLayer,
)
from mojadata.tiler2d import Tiler2D


# =============================================================================
# PATHS — adjust these for your environment
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent
INV_PATH = BASE_DIR / "inventory.gpkg"
DIST_PATH = BASE_DIR / "disturbances.gpkg"

# Mean annual temperature raster (user must provide)
# Download from WorldClim or PRISM and place here:
MAT_RASTER = BASE_DIR / "mean_annual_temp.tif"


# =============================================================================
# BOUNDING BOX
# =============================================================================

BBOX = BoundingBox(
    VectorLayer("bbox", INV_PATH),
    pixel_size=0.001,  # ~100m at this latitude
)


# =============================================================================
# TILER CONFIGURATION
# =============================================================================

def main():
    tiler = Tiler2D(BBOX, use_multiprocessing=True)

    # Classifiers
    classifiers = [
{classifiers_str}
    ]

    # Age
    age_layer = VectorLayer("initial_age", INV_PATH, "initial_age")

    # Historical / last-pass disturbance type
    hist_dist = VectorLayer("historical_disturbance_type", INV_PATH, "historical_disturbance_type")
    last_dist = VectorLayer("last_pass_disturbance_type", INV_PATH, "last_pass_disturbance_type")

    # Mean annual temperature
    mat_layer = RasterLayer(MAT_RASTER)

    # Disturbance layers (one per year)
    disturbances = [
{dist_layers_str}
    ]

    # Run the tiler
    tiler.tile(
        classifiers=classifiers,
        age=age_layer,
        historical_disturbance=hist_dist,
        last_pass_disturbance=last_dist,
        mean_annual_temp=mat_layer,
        disturbances=disturbances,
    )

    print("Tiling complete.")


if __name__ == "__main__":
    main()
'''
    return script


def run(inventory_path=None):
    """Main entry point."""
    return generate_tiler_script(inventory_path)


if __name__ == "__main__":
    run()
