"""
Mojadata tiler configuration for IWC Boothill GCBM simulation.

Auto-generated by 08_tiler_config.py.
Review and adjust paths before running.

Usage:
    python tiler.py
"""

from pathlib import Path

from mojadata.boundingbox import BoundingBox
from mojadata.layer.vectorlayer import VectorLayer
from mojadata.layer.rasterlayer import RasterLayer
from mojadata.layer.attribute import Attribute
from mojadata.config import (
    BoundingBox as BBox,
    ClassifierLayer,
    DisturbanceLayer,
)
from mojadata.tiler2d import Tiler2D


# =============================================================================
# PATHS — adjust these for your environment
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent
INV_PATH = BASE_DIR / "inventory.gpkg"
DIST_PATH = BASE_DIR / "disturbances.gpkg"

# Mean annual temperature raster (user must provide)
# Download from WorldClim or PRISM and place here:
MAT_RASTER = BASE_DIR / "mean_annual_temp.tif"


# =============================================================================
# BOUNDING BOX
# =============================================================================

BBOX = BoundingBox(
    VectorLayer("bbox", INV_PATH),
    pixel_size=0.001,  # ~100m at this latitude
)


# =============================================================================
# TILER CONFIGURATION
# =============================================================================

def main():
    tiler = Tiler2D(BBOX, use_multiprocessing=True)

    # Classifiers
    classifiers = [
        ClassifierLayer("species", INV_PATH, "species"),
        ClassifierLayer("origin", INV_PATH, "origin"),
        ClassifierLayer("si_class", INV_PATH, "si_class"),
        ClassifierLayer("growth_period", INV_PATH, "growth_period"),
        ClassifierLayer("mgmt_trajectory", INV_PATH, "mgmt_trajectory"),
    ]

    # Age
    age_layer = VectorLayer("initial_age", INV_PATH, "initial_age")

    # Historical / last-pass disturbance type
    hist_dist = VectorLayer("historical_disturbance_type", INV_PATH, "historical_disturbance_type")
    last_dist = VectorLayer("last_pass_disturbance_type", INV_PATH, "last_pass_disturbance_type")

    # Mean annual temperature
    mat_layer = RasterLayer(MAT_RASTER)

    # Disturbance layers (one per year)
    disturbances = [
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2026"),
            year=2026,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2027"),
            year=2027,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2028"),
            year=2028,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2029"),
            year=2029,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2030"),
            year=2030,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2031"),
            year=2031,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2032"),
            year=2032,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2033"),
            year=2033,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2034"),
            year=2034,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2035"),
            year=2035,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2036"),
            year=2036,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2037"),
            year=2037,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2038"),
            year=2038,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2039"),
            year=2039,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2040"),
            year=2040,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2041"),
            year=2041,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2042"),
            year=2042,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2043"),
            year=2043,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2044"),
            year=2044,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2045"),
            year=2045,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2046"),
            year=2046,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2047"),
            year=2047,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2048"),
            year=2048,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2049"),
            year=2049,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2050"),
            year=2050,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2051"),
            year=2051,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2052"),
            year=2052,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2053"),
            year=2053,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2054"),
            year=2054,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2055"),
            year=2055,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2056"),
            year=2056,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2057"),
            year=2057,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2058"),
            year=2058,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2059"),
            year=2059,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2060"),
            year=2060,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2061"),
            year=2061,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2062"),
            year=2062,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2063"),
            year=2063,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2064"),
            year=2064,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2065"),
            year=2065,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2066"),
            year=2066,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2067"),
            year=2067,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2068"),
            year=2068,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2069"),
            year=2069,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2070"),
            year=2070,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2071"),
            year=2071,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2072"),
            year=2072,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2073"),
            year=2073,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2074"),
            year=2074,
        ),
        DisturbanceLayer(
            VectorLayer("disturbance_type", DIST_PATH, "disturbance_type",
                        raw_filter="year = 2075"),
            year=2075,
        ),
    ]

    # Run the tiler
    tiler.tile(
        classifiers=classifiers,
        age=age_layer,
        historical_disturbance=hist_dist,
        last_pass_disturbance=last_dist,
        mean_annual_temp=mat_layer,
        disturbances=disturbances,
    )

    print("Tiling complete.")


if __name__ == "__main__":
    main()
